# SEGMENTASI CUSTOMER



*  Segmentasi Customer Berbasis Statistik.

    * Order Segment: Jumlah transaksi yang dilakukan oleh customer (Total SalesOrderNumber).
    * Quantity Segment: Total jumlah barang yang dibeli (Order Quantity).
    * Sales Segment: Total nilai pembelian customer, dihitung dengan rumus:**(Order Quantity × Unit Price) − Discount.**

* Segmentasi Customer dengan Metode RFM.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
url = "https://raw.githubusercontent.com/Arfi3/Office_Sales_Analysis/main/Sales.xlsx"
df = pd.read_excel(url)

df.head()

,SalesOrderNumber,OrderDate,DeliveryDate,ShipMode,CustomerKey,ProductKey,CategoryName,SubcategoryName,ProductName,UnitPrice,OrderQuantity,Discount %,ShippingCost,OrderPriority
0,IN-2017-47883,2017-01-01,2017-01-08,Standard Class,56,FUR-FU-10003447,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",25.26,5,0.5,11.92,Medium
1,IZ-2017-4680,2017-01-03,2017-01-07,Standard Class,66,FUR-NOV-10002791,Furniture,Chairs,"Novimex Swivel Stool, Set of Two",166.71,4,0.6,9.81,High
2,ID-2017-80230,2017-01-03,2017-01-09,Standard Class,64,FUR-CH-10000666,Furniture,Chairs,"SAFCO Chairmat, Black",57.39,2,0.2,8.30,Low
3,ID-2017-80230,2017-01-03,2017-01-09,Standard Class,64,FUR-CH-10000214,Furniture,Chairs,"Hon Rocking Chair, Set of Two",132.87,2,0.0,9.63,Low
4,ES-2017-4869686,2017-01-03,2017-01-07,Standard Class,63,FUR-BO-10000728,Furniture,Bookcases,"Dania Corner Shelving, Traditional",122.07,7,0.6,12.56,Medium

In [ ]:
url2="https://raw.githubusercontent.com/Arfi3/Office_Sales_Analysis/main/Customer.xlsx"
df_2 = pd.read_excel(url2)

df_2.head()

,CustomerKey,Customer,StateName,Country,Region,Market,BusinessType
0,56,Joseph Holt,New South Wales,Australia,Oceania,APAC,Consumer
1,57,Eugene Moren,Stockholm,Sweden,North,EU,Home Office
2,58,Annie Thurman,Budapest,Hungary,EMEA,EMEA,Consumer
3,59,Toby Braunhardt,Constantine,Algeria,Africa,Africa,Consumer
4,60,Nat Gilpin,Razavi Khorasan,Iran,EMEA,EMEA,Corporate

In [ ]:
df.nunique()

SalesOrderNumber    17801
OrderDate            1406
DeliveryDate         1455
ShipMode                4
CustomerKey         16874
ProductKey           5963
CategoryName            2
SubcategoryName        10
ProductName          2432
UnitPrice            2796
OrderQuantity          16
Discount %              9
ShippingCost        11144
OrderPriority           4
dtype: int64

In [ ]:
df['Total_Purchase'] = df['UnitPrice'] *df['OrderQuantity']* (1 - df['Discount %'])

In [ ]:
df.head()

,SalesOrderNumber,OrderDate,DeliveryDate,ShipMode,CustomerKey,ProductKey,CategoryName,SubcategoryName,ProductName,UnitPrice,OrderQuantity,Discount %,ShippingCost,OrderPriority,Total_Purchase
0,IN-2017-47883,2017-01-01,2017-01-08,Standard Class,56,FUR-FU-10003447,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",25.26,5,0.5,11.92,Medium,63.150
1,IZ-2017-4680,2017-01-03,2017-01-07,Standard Class,66,FUR-NOV-10002791,Furniture,Chairs,"Novimex Swivel Stool, Set of Two",166.71,4,0.6,9.81,High,266.736
2,ID-2017-80230,2017-01-03,2017-01-09,Standard Class,64,FUR-CH-10000666,Furniture,Chairs,"SAFCO Chairmat, Black",57.39,2,0.2,8.30,Low,91.824
3,ID-2017-80230,2017-01-03,2017-01-09,Standard Class,64,FUR-CH-10000214,Furniture,Chairs,"Hon Rocking Chair, Set of Two",132.87,2,0.0,9.63,Low,265.740
4,ES-2017-4869686,2017-01-03,2017-01-07,Standard Class,63,FUR-BO-10000728,Furniture,Bookcases,"Dania Corner Shelving, Traditional",122.07,7,0.6,12.56,Medium,341.796

In [ ]:
df_3 = pd.merge(df, df_2, on='CustomerKey', how='left')

In [ ]:
df_3.head()

,SalesOrderNumber,OrderDate,DeliveryDate,ShipMode,CustomerKey,ProductKey,CategoryName,SubcategoryName,ProductName,UnitPrice,...,Discount %,ShippingCost,OrderPriority,Total_Purchase,Customer,StateName,Country,Region,Market,BusinessType
0,IN-2017-47883,2017-01-01,2017-01-08,Standard Class,56,FUR-FU-10003447,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",25.26,...,0.5,11.92,Medium,63.150,Joseph Holt,New South Wales,Australia,Oceania,APAC,Consumer
1,IZ-2017-4680,2017-01-03,2017-01-07,Standard Class,66,FUR-NOV-10002791,Furniture,Chairs,"Novimex Swivel Stool, Set of Two",166.71,...,0.6,9.81,High,266.736,Lindsay Williams,Ninawa,Iraq,EMEA,EMEA,Corporate
2,ID-2017-80230,2017-01-03,2017-01-09,Standard Class,64,FUR-CH-10000666,Furniture,Chairs,"SAFCO Chairmat, Black",57.39,...,0.2,8.30,Low,91.824,Ken Lonsdale,Auckland,New Zealand,Oceania,APAC,Consumer
3,ID-2017-80230,2017-01-03,2017-01-09,Standard Class,64,FUR-CH-10000214,Furniture,Chairs,"Hon Rocking Chair, Set of Two",132.87,...,0.0,9.63,Low,265.740,Ken Lonsdale,Auckland,New Zealand,Oceania,APAC,Consumer
4,ES-2017-4869686,2017-01-03,2017-01-07,Standard Class,63,FUR-BO-10000728,Furniture,Bookcases,"Dania Corner Shelving, Traditional",122.07,...,0.6,12.56,Medium,341.796,Dorothy Dickinson,England,United Kingdom,North,EU,Consumer

In [ ]:
df_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29999 entries, 0 to 29998
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SalesOrderNumber  29999 non-null  object
 1   OrderDate         29999 non-null  datetime64[ns]
 2   DeliveryDate      29829 non-null  datetime64[ns]
 3   ShipMode          29999 non-null  object
 4   CustomerKey       29999 non-null  int64
 5   ProductKey        29999 non-null  object
 6   CategoryName      29999 non-null  object
 7   SubcategoryName   29999 non-null  object
 8   ProductName       29999 non-null  object
 9   UnitPrice         29999 non-null  float64
 10  OrderQuantity     29999 non-null  int64
 11  Discount %        29999 non-null  float64
 12  ShippingCost      29999 non-null  float64
 13  OrderPriority     29999 non-null  object
 14  Total_Purchase    29999 non-null  float64
 15  Customer          29999 non-null  object
 16  StateName         29999 non-null  object
 17  Country           29999 non-null  object
 18  Region            29999 non-null  object
 19  Market            29999 non-null  object
 20  BusinessType      29999 non-null  object
dtypes: datetime64[ns](2), float64(4), int64(2), object(13)
memory usage: 4.8+ MB

In [ ]:
# =========================
# AGREGASI PER CUSTOMER
# =========================
customer_agg = df_3.groupby('Customer').agg({
    'SalesOrderNumber': 'nunique',
    'OrderQuantity': 'sum',
    'Total_Purchase': 'sum'
}).reset_index()

customer_agg.columns = ['Customer', 'Total_Order', 'Total_Quantity', 'Total_Sales']

In [ ]:
customer_agg.head()

          Customer  Total_Order  Total_Quantity  Total_Sales
0    Aaron Bergman           24             147     5933.559
1    Aaron Hawkins           23             111     5769.676
2   Aaron Smayling           25             138     5013.556
3  Adam Bellavance           29             177    10674.047
4        Adam Hart           34             194     9835.469

In [ ]:
# =========================
# SEGMENTASI STATISTIK
# =========================
def label_tier(series, labels):
    return pd.qcut(series, q=3, labels=labels, duplicates='drop')

# Total Order
customer_agg['Order_Segment'] = label_tier(
    customer_agg['Total_Order'],
    ['Silver', 'Gold', 'Platinum']
)

# Quantity
customer_agg['Quantity_Segment'] = label_tier(
    customer_agg['Total_Quantity'],
    ['Regular', 'Champion', 'King']
)

# Sales
customer_agg['Sales_Segment'] = label_tier(
    customer_agg['Total_Sales'],
    ['Prime', 'Elite', 'Diamond']
)

# =========================
# HASIL
# =========================
customer_agg.head()

,Customer,Total_Order,Total_Quantity,Total_Sales,Order_Segment,Quantity_Segment,Sales_Segment
0,Aaron Bergman,24,147,5933.559,Gold,King,Elite
1,Aaron Hawkins,23,111,5769.676,Gold,Regular,Elite
2,Aaron Smayling,25,138,5013.556,Gold,Champion,Elite
3,Adam Bellavance,29,177,10674.047,Platinum,King,Diamond
4,Adam Hart,34,194,9835.469,Platinum,King,Diamond

In [ ]:
# =========================
# SEGMENTASI DENGAN RFM
# =========================
df_3['OrderDate'] = pd.to_datetime(df_3['OrderDate'])

# ambil tanggal terakhir di dataset
latest_date = df_3['OrderDate'].max()

# hitung recency (dalam hari)
rfm = df_3.groupby('Customer').agg({
    'OrderDate': lambda x: (latest_date - x.max()).days,
    'SalesOrderNumber': 'nunique',
    'Total_Purchase': 'sum'
}).reset_index()

rfm.columns = ['Customer', 'Recency', 'Frequency', 'Monetary']

In [ ]:
rfm.head()

          Customer  Recency  Frequency   Monetary
0    Aaron Bergman       16         24   5933.559
1    Aaron Hawkins       12         23   5769.676
2   Aaron Smayling       23         25   5013.556
3  Adam Bellavance       35         29  10674.047
4        Adam Hart        2         34   9835.469

In [ ]:
rfm['R_Score'] = pd.qcut(rfm['Recency'], q=3, labels=[3,2,1])
rfm['F_Score'] = pd.qcut(rfm['Frequency'], q=3, labels=[1,2,3])
rfm['M_Score'] = pd.qcut(rfm['Monetary'], q=3, labels=[1,2,3])

In [ ]:
rfm['RFM_Total'] = rfm[['R_Score','F_Score','M_Score']].astype(int).sum(axis=1)

In [ ]:
rfm['Segment'] = pd.qcut(
    rfm['RFM_Total'],
    q=3,
    labels=['Low', 'Medium', 'High']
)

In [ ]:
rfm.head()

,Customer,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Score,RFM_Total,Segment
0,Aaron Bergman,16,24,5933.559,2,2,2,222,6,Medium
1,Aaron Hawkins,12,23,5769.676,3,2,2,322,7,Medium
2,Aaron Smayling,23,25,5013.556,2,2,2,222,6,Medium
3,Adam Bellavance,35,29,10674.047,2,3,3,233,8,High
4,Adam Hart,2,34,9835.469,3,3,3,333,9,High

In [ ]:
segmentasi_customer= pd.merge(customer_agg, rfm, on='Customer', how='inner')

In [ ]:
segmentasi_customer.head()

,Customer,Total_Order,Total_Quantity,Total_Sales,Order_Segment,Quantity_Segment,Sales_Segment,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Score,RFM_Total,Segment
0,Aaron Bergman,24,147,5933.559,Gold,King,Elite,16,24,5933.559,2,2,2,222,6,Medium
1,Aaron Hawkins,23,111,5769.676,Gold,Regular,Elite,12,23,5769.676,3,2,2,322,7,Medium
2,Aaron Smayling,25,138,5013.556,Gold,Champion,Elite,23,25,5013.556,2,2,2,222,6,Medium
3,Adam Bellavance,29,177,10674.047,Platinum,King,Diamond,35,29,10674.047,2,3,3,233,8,High
4,Adam Hart,34,194,9835.469,Platinum,King,Diamond,2,34,9835.469,3,3,3,333,9,High

In [ ]:
segmentasi_customer.to_csv('customer_segmentation.csv', index=False)